# Generated by Django 3.2 on 2024-08-04 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_title_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
