# Generated by Django 3.2 on 2024-08-05 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_subscribe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
